# Site settings
title: Nick DePalma, PhD, Robotics and Interaction
email: ndepalma@alum.mit.edu
description: ""
url: "https://ndepalma.github.io"
#url: "http://localhost:4000/"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  research:
    output: true
  thoughts:
    output: true

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: mine
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
